/**
 * The two recipes: what Meadowbrook is, and what Sourwood is.
 *
 * Split out of tools/genworld.mjs alongside draft.js so that the browser can
 * run them too -- `npm run genworld` writes the starter files from these, and
 * world/generate.js calls the same functions with a different seed and a
 * jittered shape to make a place nobody has seen before. One recipe, two
 * callers, so a generated island is the same KIND of thing as the shipped one:
 * same cast, same interiors, same rules about who lets you in the front door.
 *
 * EVERY SHAPE NUMBER IS AN ARGUMENT, and every one of them defaults to what the
 * shipped world was authored with. That is what makes the split safe to check:
 * regenerate with no options and the JSON on disk has to come back byte for
 * byte, or the refactor changed a world while claiming not to.
 *
 * The people, their dialog and the interiors they link to are NOT parameters.
 * A generated island moves the coastline, the trees and the houses; it does not
 * invent a villager, because a villager without a script to speak is worse
 * than no villager at all.
 */

import { Draft } from './draft.js';

// ===========================================================================
// MEADOWBROOK -- an island
// ===========================================================================
// A round island with a beach all the way round, a bluff over its north half,
// and the town on the flat ground south of it. Everything is laid out from the
// coastline inward, so moving the coast moves the town with it.
export function meadowbrook({
  seed = 0x5eed1234,
  // 64 across, where it used to be 44. The island is a fixed FRACTION of its
  // grid (R/W is unchanged), so everything below is still authored against the
  // centre and the radius -- growing the world is these two numbers and the
  // counts at the bottom, not a re-survey of the town.
  size = 64,
  radius = 27,
  // Three harmonics of the bearing from the centre, as [times round, how far,
  // where it starts]: enough to read as a natural shore, few enough that no bay
  // ever pinches the island in two. A generator may move all nine numbers; what
  // it must not do is add a fourth, faster harmonic, which is where a coastline
  // stops being a coastline and starts being a gear.
  wobble = [[3, 0.10, 0.6], [5, 0.07, 2.1], [8, 0.045, 4.0]],
  // The bluff, as an offset north of centre and a radius. It has to stay over
  // the middle columns: `rampNorth` cuts the only way up it at cx and cx-1, and
  // a bluff that has slid east of those is a cliff with no path.
  bluff = [0, -10, 9.6],
  // Discs of fresh water, offset from the centre. Two, overlapping, because one
  // circle reads as a puddle someone drew with a compass.
  pond = [[-12, 6, 4.3], [-9, 9, 2.7]],
  meta = {
    id: 'meadowbrook',
    name: 'Meadowbrook',
    note: 'Generated by tools/genworld.mjs; safe to hand-edit.',
  },
} = {}) {
  const d = new Draft(size, size, seed);
  const cx = Math.round(size / 2), cz = Math.round(size / 2), R = radius;

  // Coastline.
  for (let z = 0; z < d.H; z++) {
    for (let x = 0; x < d.W; x++) {
      const nx = (x + 0.5 - cx) / R, nz = (z + 0.5 - cz) / R;
      const a = Math.atan2(nz, nx);
      let wob = 1;
      for (const [k, amp, phase] of wobble) wob += amp * Math.sin(k * a + phase);
      const r = Math.hypot(nx, nz) / wob;
      d.surf[z][x] = r < 0.70 ? 'g' : r < 0.84 ? 's' : 'w';
    }
  }

  // The bluff: raised ground over the north half, whose south face is the cliff
  // the whole town sits under. One way down, which is what makes it a landmark
  // rather than a hill.
  d.disc(d.elev, cx + bluff[0], cz + bluff[1], bluff[2], '1');
  for (let z = 0; z < d.H; z++) {
    for (let x = 0; x < d.W; x++) if (d.surf[z][x] === 'w') d.elev[z][x] = '0';
  }

  // Freshwater pond in the west meadow, well inside the shore.
  for (const [dx, dz, r] of pond) d.disc(d.surf, cx + dx, cz + dz, r, 'w');

  const rampZ = d.rampNorth(cx - 1);
  d.rampNorth(cx);

  // Paving, aimed generously; `pave` trims it wherever it overshoots the land.
  d.pave(cx - 6, cz - 18, cx + 5, cz - 13, { level: '1' });   // lookout apron, up top
  d.pave(cx - 1, cz - 13, cx, cz - 3, { level: '1' });        // bluff spine, to the cliff
  d.pave(cx - 1, rampZ, cx, cz + 15, { level: '0' });         // road off the ramp, into town
  d.pave(cx - 11, cz + 10, cx + 13, cz + 15, { level: '0' }); // town plaza
  d.pave(cx - 3, cz + 16, cx + 2, cz + 28, { level: '0' });   // boardwalk to the south beach

  const lookout = d.placeNear('gate.north', 'building.gate', cx - 4, cz - 16, ['c', 'g'], 8,
    { label: 'Meadowbrook Lookout' }, '1');
  const home = d.placeNear('home.player', 'building.home', cx - 10, cz + 4, ['g'], 10,
    { label: "Tyler's House", interior: 'worlds/interiors/home-tyler.json' }, '0');
  const store = d.placeNear('store.nook', 'building.store', cx + 8, cz + 3, ['g'], 10,
    { label: 'General Store', interior: 'worlds/interiors/store-nook.json' }, '0');

  // THE NEIGHBOURS. Three houses round the plaza, each with somebody living in
  // it, and each interior a place you are not welcome until you have met them
  // (the private zone is declared in the interior file -- see
  // docs/WORLD_FORMAT.md). They are spread deliberately: the whole feature is
  // walking up to a stranger, so the three of them must not be findable from
  // one spot on the square.
  const cottage = d.placeNear('home.bramble', 'building.cottage', cx - 14, cz + 14, ['g'], 10,
    { label: "Bramble's Cottage", interior: 'worlds/interiors/home-bramble.json' }, '0');
  const cabin = d.placeNear('home.wren', 'building.cabin', cx + 4, cz + 19, ['g', 's'], 10,
    { label: "Wren's Cabin", interior: 'worlds/interiors/home-wren.json' }, '0');
  const bungalow = d.placeNear('home.tobin', 'building.bungalow', cx + 15, cz + 8, ['g'], 10,
    { label: "Tobin's Bungalow", interior: 'worlds/interiors/home-tobin.json' }, '0');

  // Approaches, drawn AFTER placement so a building that had to shuffle takes
  // its path with it. Doors face south, so the approach starts below them.
  d.pathL(home[0] + 1, home[1] + 3, cx - 1, cz + 11, { level: '0' });
  d.pathL(store[0] + 2, store[1] + 4, cx, cz + 11, { level: '0' });
  d.pathL(cottage[0] + 1, cottage[1] + 3, cx - 10, cz + 12, { level: '0' });
  d.pathL(cabin[0] + 2, cabin[1] + 3, cx + 1, cz + 20, { level: '0' });
  d.pathL(bungalow[0] + 2, bungalow[1] + 3, cx + 11, cz + 12, { level: '0' });
  d.pathL(lookout[0] + 2, lookout[1] + 2, cx - 1, cz - 13, { level: '1' });

  // The people, standing on their own doorsteps -- the tile directly south of
  // the door, which is the one tile outside every house that placement has
  // already proved you can walk to. `roam` is what sends them
  // wandering (sim/behaviors.js), and it is sized to keep each of them within
  // sight of their own front garden: someone you have to hunt for is someone
  // whose house you will burgle instead.
  d.person({
    id: 'folk.pim',
    type: 'folk.villager',
    tile: [cx + 1, cz + 12],
    facing: 'west',
    props: { name: 'Pim', title: 'Loiterer', roam: 6 },
    dialog: {
      start: 'open',
      nodes: {
        open: {
          branch: [
            { when: { flag: 'gave' }, to: 'after' },
            { when: { visits: 3 }, to: 'third' },
            { to: 'hello' },
          ],
        },
        hello: {
          text: [
            'Morning. Chickens been at the flowerbed again.',
            "Marla's shop is the blue roof, if you're looking. She's fair.",
          ],
          then: 'menu',
        },
        third: { text: 'You do walk about a lot, don\'t you.', then: 'menu' },
        menu: {
          text: 'Anything else?',
          choices: [
            {
              text: 'Could you spare a flower?',
              when: { room: { type: 'item.flower', count: 1 } },
              to: 'gift',
            },
            { text: 'Where does that gate go?', to: 'gate' },
            { text: 'Who else lives here?', to: 'folk' },
            { text: "I'll let you get on.", to: 'bye' },
          ],
        },
        gift: {
          text: 'Take one, they grow back faster than I can pick them.',
          do: [{ give: { type: 'item.flower', count: 1 } }, { set: 'gave' }],
          then: 'menu',
        },
        gate: {
          text: 'North, out of town. Long walk and nothing at the end of it yet.',
          then: 'menu',
        },
        folk: {
          text: [
            "Bramble's the one in the green apron, west side. Wren's down on the sand. Tobin you'll smell before you see -- solder.",
            "Say hello before you go walking into their houses. They're funny about that, and I'd be too.",
          ],
          then: 'menu',
        },
        after: { text: "Flowerbed's holding up. Mind the chickens.", then: 'menu' },
        bye: { text: 'Right you are.' },
      },
    },
  });

  d.person({
    id: 'folk.bramble',
    type: 'folk.gardener',
    tile: [cottage[0] + 1, cottage[1] + 3],
    facing: 'south',
    props: { name: 'Bramble', title: 'Grows things', roam: 6 },
    dialog: {
      start: 'open',
      nodes: {
        open: {
          branch: [
            { when: { friend: true }, to: 'welcome' },
            { to: 'hello' },
          ],
        },
        hello: {
          text: [
            "Don't mind me, I'm up to my wrists in it.",
            "Bramble. That's my cottage behind you -- the green roof. Door's open to you now we've met.",
          ],
          then: 'menu',
        },
        welcome: {
          text: 'Back again. Go on in if you like, I\'ll be out here a while yet.',
          then: 'menu',
        },
        menu: {
          text: 'Something you wanted?',
          choices: [
            {
              text: 'Anything growing worth having?',
              when: { room: { type: 'item.mushroom', count: 1 } },
              to: 'gift',
            },
            { text: 'What is there to do round here?', to: 'advice' },
            { text: 'Just passing.', to: 'bye' },
          ],
        },
        gift: {
          text: 'Take these. Came up under the pines after the rain.',
          do: [{ give: { type: 'item.mushroom', count: 2 } }],
          then: 'menu',
        },
        advice: {
          text: [
            "Walk about. Talk to folk. Half the doors in this town open once you've said hello to whoever's behind them.",
            "The other half you can try, but you'll not be in there long.",
          ],
          then: 'menu',
        },
        bye: { text: 'Mind the beds on your way past.' },
      },
    },
  });

  d.person({
    id: 'folk.wren',
    type: 'folk.fisher',
    tile: [cabin[0] + 2, cabin[1] + 3],
    facing: 'south',
    props: { name: 'Wren', title: 'Works the shallows', roam: 7 },
    dialog: {
      start: 'open',
      nodes: {
        open: {
          branch: [
            { when: { friend: true }, to: 'welcome' },
            { to: 'hello' },
          ],
        },
        hello: {
          text: [
            'Careful, you nearly went in.',
            "Wren. Cabin's mine, the low one on the sand. Come in out of the weather whenever, now I know your face.",
          ],
          then: 'menu',
        },
        welcome: { text: "Tide's out. Good day for it.", then: 'menu' },
        menu: {
          text: 'Well?',
          choices: [
            {
              text: 'Found any shells?',
              when: { room: { type: 'item.shell', count: 1 } },
              to: 'gift',
            },
            { text: 'Marla buys shells, I hear.', to: 'trade' },
            { text: "I'll leave you to it.", to: 'bye' },
          ],
        },
        gift: {
          text: "Here. I've a bucket of them and one pair of hands.",
          do: [{ give: { type: 'item.shell', count: 1 } }],
          then: 'menu',
        },
        trade: {
          text: 'She does, and she pays properly for them. Don\'t tell her I said so.',
          then: 'menu',
        },
        bye: { text: 'Aye. Watch the current.' },
      },
    },
  });

  d.person({
    id: 'folk.tobin',
    type: 'folk.tinker',
    tile: [bungalow[0] + 2, bungalow[1] + 3],
    facing: 'south',
    props: { name: 'Tobin', title: 'Mends what he can', roam: 5 },
    dialog: {
      start: 'open',
      nodes: {
        open: {
          branch: [
            { when: { friend: true }, to: 'welcome' },
            { to: 'hello' },
          ],
        },
        hello: {
          text: [
            'Hm? Oh. Hello.',
            "Tobin. The long house with the orange roof. You're welcome in it, though I warn you there's nowhere to sit.",
          ],
          then: 'menu',
        },
        welcome: { text: "It's you. Mind the crates.", then: 'menu' },
        menu: {
          text: 'Was there something?',
          choices: [
            {
              text: 'Could you use a few sticks?',
              when: { has: { type: 'item.stick', count: 2 } },
              to: 'trade',
            },
            { text: 'What are you making?', to: 'making' },
            { text: 'Nothing. Sorry.', to: 'bye' },
          ],
        },
        trade: {
          text: "I could. Here's for your trouble.",
          do: [{ take: { type: 'item.stick', count: 2 } }, { coins: 18 }],
          then: 'menu',
        },
        making: {
          text: "Nothing. Mending. There's a difference and it's most of my week.",
          then: 'menu',
        },
        bye: { text: 'Right. Mind the step.' },
      },
    },
  });

  // Counts scale with the island, not with the old grid: a 64-tile world with
  // a 44-tile world's worth of trees in it reads as a lawn.
  const counts = {
    boulder: d.scatter('boulder', 'rock.large', 11, ['g', 's']),
    oak: d.scatter('oak', 'tree.oak', 70, ['g']),
    pine: d.scatter('pine', 'tree.pine', 38, ['g']),
    palm: d.scatter('palm', 'tree.palm', 40, ['s']),
    rock: d.scatter('rock', 'rock.small', 36, ['g', 's']),
    // Last, so the birds dodge the scenery rather than the other way round:
    // trees claim tiles, and a chicken is only ever standing on one.
    chicken: d.flock('chicken', 'chicken', 9, home[0] + 1, home[1] + 5, 5, ['g', 'c']),

    // Foraging, sorted by where the thing would actually be: shells wash up on
    // the beach, mushrooms come up in the shade of the woods, apples fall near
    // the house someone planted the trees behind. Scattering all five kinds
    // uniformly over the island would be quicker to write and would make the
    // whole map read as one undifferentiated place to hoover up.
    shell: d.litter('shell', 'item.shell', 16, ['s']),
    stone: d.litter('stone', 'item.stone', 12, ['s', 'g']),
    stick: d.litter('stick', 'item.stick', 14, ['g']),
    flower: d.litter('flower', 'item.flower', 14, ['g']),
    mushroom: d.litter('mushroom', 'item.mushroom', 9, ['g'], { cx: cx + 8, cz: cz + 16, radius: 12 }),
    apple: d.litter('apple', 'item.apple', 8, ['g'], { cx: home[0] + 1, cz: home[1] + 4, radius: 7 }),
  };

  return {
    draft: d,
    counts,
    world: d.toWorld({
      meta,
      terrain: { form: 'island' },
      spawn: { tile: [cx - 1, rampZ + 3], facing: 'south' },
    }),
  };
}

// ===========================================================================
// SOURWOOD -- a holler
// ===========================================================================
// Long and narrow, because that is the shape of the landform: a creek in the
// bottom, a road beside it, benches stepping up both walls, the head closed off
// at the north and the mouth open at the south. The two walls are what the
// renderer continues into ridges, so the layout's job is to be climbing by the
// time it reaches the east and west edges.
export function sourwood({
  seed = 0xc0ffee31,
  // 42 x 84, where it used to be 30 x 60: the same holler, longer and with
  // more bottomland in it. Everything below is written against W, H and FLOOR,
  // so the shape survives the change -- the creek keeps the same number of
  // bends over a longer run, and the walls still reach the top bench before
  // they reach the edge.
  width = 42,
  height = 84,
  floor = 9,                     // half-width of the bottomland, in tiles
  // Two tiles per bench, not one. A single-tile bench is severed by the first
  // tree that lands on it -- and a bench you cannot walk along is scenery the
  // player can see, stand next to, and never use.
  bench = 2.2,
  // The creek's wander, as [per-row frequency, half-width, phase]. Frequencies
  // are per ROW so they scale with the length: a longer valley with a fixed
  // bend count would be a corkscrew.
  creekWave = [[0.0786, 4.5, 0.5], [0.193, 1.3, 1.9]],
  // Rows where the creek is forded, and rows where a trail climbs a wall as
  // [row, which way]. Both are given rather than derived because both are about
  // the SHAPE of the valley -- where it is worth crossing, where the wall is
  // climbable -- and a generator that moves the length has to move them too.
  fords = [24, 45, 64, 77],
  trails = [[28, -1], [52, 1]],
  // Which row each landmark wants to stand on. `placeNear` does the rest.
  sites = { gate: 73, home: 36, store: 62 },
  spawnRow = 42,
  meta = {
    id: 'sourwood',
    name: 'Sourwood Holler',
    note: 'Generated by tools/genworld.mjs; safe to hand-edit.',
  },
} = {}) {
  const d = new Draft(width, height, seed);
  const axis = d.W / 2;          // the valley runs due south
  const FLOOR = floor;
  const BENCH = bench;

  /**
   * WHY THE WALLS RUN STRAIGHT
   * --------------------------
   * A bench's elevation depends on x alone, so every bench is one unbroken
   * strip from the head to the mouth. Let the wall wander with the creek
   * instead and each bench acquires a north-south step every few rows -- a
   * cliff, since two tiles at different heights never share an edge height --
   * which chops the hillside into a few hundred flat shelves you can see and
   * cannot reach. The wander belongs to the creek, which has it; the walls
   * just have to hold the valley.
   */
  const creek = (z) => creekWave.reduce((c, [k, amp, phase]) => c + amp * Math.sin(z * k + phase), axis);

  /**
   * The mouth. Flaring the bottomland outward over the last rows is what makes
   * the south edge genuinely open: the benches are pushed off the map rather
   * than lowered, so no shelf is ever stranded above a step it cannot descend.
   */
  // Linear, and deliberately slower than one tile per row: a boundary that
  // sweeps outward faster than that skips over a bench, stranding it above a
  // step with nothing beside it at the same height.
  const flare = (z) => (z < d.H - 22 ? 0 : 0.9 * (z - (d.H - 22)));

  for (let z = 0; z < d.H; z++) {
    const c = creek(z), fh = FLOOR + flare(z);
    // The head of the holler, where the ground closes over the top of it.
    const head = z < 13 ? Math.min(4, Math.round((13 - z) * 0.44)) : 0;
    for (let x = 0; x < d.W; x++) {
      const wall = Math.min(4, Math.max(0, Math.ceil((Math.abs(x + 0.5 - axis) - fh) / BENCH)));
      const e = Math.max(wall, head);
      d.elev[z][x] = String(e);

      // Creek in the bottom, gravel bar beside it. Both only where it is flat,
      // so the creek rises out of the head rather than running down a cliff.
      const dc = Math.abs(x + 0.5 - c);
      d.surf[z][x] = e > 0 ? 'g' : dc < 1.15 ? 'w' : dc < 1.95 ? 's' : 'g';
    }
  }

  // Low-water crossings. The creek runs the whole length of the only flat
  // ground there is, so without a ford the two banks are two different places
  // -- and the one with the house on it is the one you cannot reach.
  for (const z of fords) {
    for (let dz = 0; dz < 2; dz++) {
      for (let x = 0; x < d.W; x++) if (d.surf[z + dz][x] === 'w') d.surf[z + dz][x] = 's';
    }
    d.pave(0, z, d.W - 1, z + 1, { level: '0', onto: ['g'] });
  }

  // The road runs the length of the bottom, east of the creek and clear of it.
  for (let z = 0; z < d.H; z++) {
    const x0 = Math.round(creek(z)) + 4;
    d.pave(x0, z, x0 + 1, z, { level: '0', onto: ['g'] });
  }

  // One trail up each wall, from beside the road. Each climbs every bench its
  // row has, and since the benches are unbroken strips, one trail per side is
  // enough to make the whole hillside walkable.
  for (const [z, dir] of trails) d.trail(z, Math.round(creek(z)) + 6 * dir, dir);

  const gate = d.placeNear('gate.mouth', 'building.gate', Math.round(creek(sites.gate)) + 2, sites.gate, ['c', 'g'], 10,
    { label: 'Sourwood Holler' }, '0');
  const home = d.placeNear('home.holler', 'building.home', Math.round(creek(sites.home)) - 8, sites.home, ['g'], 11,
    { label: 'The Old Place', interior: 'worlds/interiors/home-holler.json' }, '0');
  const store = d.placeNear('store.branch', 'building.store', Math.round(creek(sites.store)) + 6, sites.store, ['g'], 11,
    { label: 'Branch Store', interior: 'worlds/interiors/store-branch.json' }, '0');

  // Each door out to the road. The road is the only through-line in a holler,
  // so everything hangs off it.
  d.pathL(home[0] + 1, home[1] + 3, Math.round(creek(home[1] + 4)) + 4, home[1] + 4, { level: '0' });
  d.pathL(store[0] + 2, store[1] + 4, Math.round(creek(store[1] + 5)) + 4, store[1] + 5, { level: '0' });
  d.pathL(gate[0] + 2, gate[1] + 2, Math.round(creek(gate[1] + 3)) + 4, gate[1] + 3, { level: '0' });

  const counts = {
    boulder: d.scatter('boulder', 'rock.large', 18, ['g', 's'], 4200, '0'),
    pine: d.scatter('pine', 'tree.pine', 140, ['g'], 4200),
    oak: d.scatter('oak', 'tree.oak', 80, ['g'], 4200),
    rock: d.scatter('rock', 'rock.small', 54, ['g', 's'], 4200),
    // Down in the bottomland by the old place, not up a wall: a chicken keeps
    // to the patch it starts in, so the patch has to be somewhere you walk past.
    chicken: d.flock('chicken', 'chicken', 7, home[0] + 1, home[1] + 5, 4, ['g', 'c']),

    // A holler forages differently from an island: no shells, and the pebbles
    // are on the gravel bars in the creek bottom rather than on a beach.
    stick: d.litter('stick', 'item.stick', 20, ['g']),
    mushroom: d.litter('mushroom', 'item.mushroom', 16, ['g']),
    stone: d.litter('stone', 'item.stone', 15, ['s']),
    flower: d.litter('flower', 'item.flower', 13, ['g']),
    apple: d.litter('apple', 'item.apple', 7, ['g'], { cx: home[0] + 1, cz: home[1] + 4, radius: 7 }),
  };

  return {
    draft: d,
    counts,
    world: d.toWorld({
      meta,
      terrain: { form: 'holler', open: ['south'] },
      spawn: { tile: [Math.round(creek(spawnRow)) + 4, spawnRow], facing: 'south' },
      // A holler holds its haze. Pulling the fog in is most of what separates
      // "steep valley" from "field with a hill either side".
      ambience: { fog: [18, 58] },
    }),
  };
}
