#!/usr/bin/env node
/**
 * Validate the Turnip & Timber catalogue and bundle it into one kit.
 *
 * WHY A BUNDLE EXISTS AT ALL
 * --------------------------
 * The three hundred files under public/kits/furniture are the truth: one
 * product per file, editable on its own, reviewable on its own (see
 * tools/make-catalog.mjs). What they are not is a good way to LOAD a shop.
 * `Kits.loadAll` fetches one file per entry, and a world declaring three
 * hundred of them is three hundred round trips before the door opens.
 *
 * So this reads all three hundred, checks every one of them through the real
 * `parseKit` -- the same function the game runs, not a second implementation of
 * it -- and writes them out as a single kit file the game loads in one request.
 * The bundle is generated, never edited, and regenerated by `npm run catalog`
 * (which `predev` and `prebuild` both run, so it cannot go stale in a build).
 *
 * VALIDATING HERE AND NOT ONLY IN THE BROWSER is the other half of its keep. A
 * mask row of the wrong length in one of three hundred files is a KitError at
 * runtime naming a file nobody was looking at; here it is a message before the
 * bundle is written, and the previous good bundle is still on disk.
 *
 * Usage:  node tools/catalog.mjs [--check]
 *
 *   --check  validate and compare against the bundle on disk without writing.
 *            Exits non-zero if they differ, so CI can refuse a stale bundle.
 */

import fs from 'node:fs';
import path from 'node:path';
import { parseKit, KitError } from '../src/world/kit.js';

const SRC = 'public/kits/furniture';
const OUT = 'public/kits/turnip-catalog.kit.json';
const CHECK = process.argv.includes('--check');

const files = fs.readdirSync(SRC).filter((f) => f.endsWith('.kit.json')).sort();
if (!files.length) {
  console.error(`no kit files in ${SRC} -- run "node tools/make-catalog.mjs" first`);
  process.exit(1);
}

const types = {};
const owner = new Map();
let objects = 0, items = 0, failed = 0;

for (const file of files) {
  const at = path.join(SRC, file);
  let raw;
  try {
    raw = JSON.parse(fs.readFileSync(at, 'utf8'));
  } catch (e) {
    console.error(`${at}: not valid JSON: ${e.message}`);
    failed++;
    continue;
  }
  try {
    // Parsed for its errors, and then the RAW types are what get bundled: what
    // `parseKit` returns is the game's in-memory shape (radians, numbers,
    // derived part splits) and re-serialising that would produce a bundle the
    // parser could not read back.
    parseKit(raw, at);
  } catch (e) {
    console.error(`${at}: ${e instanceof KitError ? e.message : e.stack}`);
    failed++;
    continue;
  }
  for (const [id, type] of Object.entries(raw.types)) {
    if (owner.has(id)) {
      console.error(`${at}: "${id}" is already defined by ${owner.get(id)}`);
      failed++;
      continue;
    }
    owner.set(id, at);
    types[id] = type;
    if ((type.kind ?? 'object') === 'item') items++; else objects++;
  }
}

if (failed) {
  console.error(`\n${failed} file(s) rejected -- the bundle was not written.`);
  process.exit(1);
}

const bundle = {
  format: 'tw.kit',
  version: 1,
  meta: { id: 'turnip.catalogue', name: 'Turnip & Timber Catalogue' },
  types,
};

// Parsed once more as a whole, because a bundle is a kit and cross-file
// mistakes only exist once the files are in one: a flat-pack pointing at a
// fixture that lives in somebody else's file passes per-file and fails here.
parseKit(bundle, OUT);

const json = `${JSON.stringify(bundle)}\n`;

if (CHECK) {
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (have !== json) {
    console.error(`${OUT} is stale -- run "npm run catalog"`);
    process.exit(1);
  }
  console.log(`${files.length} files, ${objects} fixtures + ${items} items: bundle is current`);
} else {
  fs.writeFileSync(OUT, json);
  console.log(`${files.length} files -> ${OUT} (${objects} fixtures, ${items} items, ${(json.length / 1024).toFixed(0)} KB)`);
}
