import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { allSettlers } from './neighborhood.mjs';

const OUT = fileURLToPath(new URL('../public/worlds/interiors/', import.meta.url));
const NEIGHBORS = [
  ['lark', 'Lark', 'Cabin'], ['juniper', 'Juniper', 'Bungalow'],
  ['alder', 'Alder', 'Cottage'], ['fern', 'Fern', 'Cabin'], ['hollis', 'Hollis', 'Bungalow'],
  ['coral', 'Coral', 'Cottage'], ['selkie', 'Selkie', 'Cabin'],
  ['heather', 'Heather', 'Cottage'], ['gale', 'Gale', 'Cabin'], ['briar', 'Briar', 'Bungalow'],
  ['mesa', 'Mesa', 'Cottage'], ['flint', 'Flint', 'Cabin'], ['sora', 'Sora', 'Bungalow'],
  ['ember', 'Ember', 'Cottage'], ['basalt', 'Basalt', 'Cabin'],
  ['reed', 'Reed', 'Cottage'], ['marsh', 'Marsh', 'Cabin'],
  ['kelp', 'Kelp', 'Cottage'], ['chalk', 'Chalk', 'Cabin'], ['morrow', 'Morrow', 'Bungalow'],
];

// The two hundred settlers, appended AFTER the original twenty so every
// existing index -- and therefore every existing interior file -- is
// regenerated byte-for-byte. Their rooms come from the same press.
for (const s of allSettlers()) NEIGHBORS.push([s.id, s.name, s.home]);

const AMBIENCE = [
  ['#172019', '#dcebd0', '#667552'], ['#201b16', '#f1dfc4', '#7c684d'],
  ['#172027', '#d2e6ee', '#536d79'], ['#21191c', '#efd8df', '#785761'],
  ['#1d1d16', '#e9e7c8', '#73704a'],
];

function rows(width, height, tile) {
  return Array.from({ length: height }, (_, z) =>
    Array.from({ length: width }, (_, x) => tile(x, z)).join(''));
}

function makeInterior([id, name, home], index) {
  // The 5 x 4 dimension combinations, cycled: with two hundred and twenty
  // rooms the plans repeat, and the rug and the ambience are what keep two
  // same-sized rooms from being one room twice. The modulo keeps the first
  // twenty indices exactly where the un-cycled formula put them.
  const width = 12 + (index % 5);
  const height = 10 + (Math.floor(index / 5) % 4);
  const leftExit = Math.floor(width / 2) - 1;
  const rugX = 2 + (index % Math.max(1, width - 7));
  const rugZ = 3 + (index % Math.max(1, height - 7));
  const [sky, hemiSky, hemiGround] = AMBIENCE[index % AMBIENCE.length];
  const surface = rows(width, height, (x, z) => {
    if (z === height - 1 && (x === leftExit || x === leftExit + 1)) return 't';
    if (x === 0 || x === width - 1 || z === 0 || z === height - 1) return '#';
    if (x >= rugX && x < rugX + 2 && z >= rugZ && z < rugZ + 2) return 'r';
    return 'w';
  });
  const elevation = rows(width, height, (x, z) => {
    if (z === height - 1 && (x === leftExit || x === leftExit + 1)) return '0';
    return x === 0 || x === width - 1 || z === 0 || z === height - 1 ? '4' : '0';
  });
  const zones = rows(width, height, (x, z) => {
    if (z === height - 1 && (x === leftExit || x === leftExit + 1)) return 'h';
    return x === 0 || x === width - 1 || z === 0 || z === height - 1 ? '.' : 'h';
  });
  const flags = rows(width, height, () => '.');

  return {
    format: 'tw.world', version: 1, kind: 'interior',
    meta: {
      id: `home.${id}.interior`,
      name: `${name}'s ${home}`,
      note: `Interior of home.${id}. Generated by tools/genneighbors.mjs. PRIVATE: see zones.`,
    },
    grid: { width, height, tileSize: 1 },
    ambience: { music: 'home', sky, hemiSky, hemiGround, sun: 0.85, hemi: 2.15 },
    zones: { home: { owner: `folk.${id}`, label: `${name}'s ${home}` } },
    layers: {
      surface: { palette: { '#': 'wall', w: 'floor.wood', t: 'floor.tile', r: 'rug' }, data: surface },
      elevation: { palette: { 0: '0', 4: '4' }, data: elevation },
      flags: { palette: { '.': 'none' }, data: flags },
      zones: { palette: { '.': 'none', h: 'home' }, data: zones },
    },
    objects: [
      { id: 'shelf', type: 'furn.shelf', tile: [1, 1], props: { label: `${name}'s Shelf` } },
      { id: 'bed', type: 'furn.bed', tile: [width - 3, 2] },
      { id: 'table', type: 'furn.table', tile: [3, height - 4] },
      { id: 'chair', type: 'furn.chair', tile: [2, height - 3], rotation: index % 2 ? 90 : 270 },
      { id: 'plant', type: 'furn.plant', tile: [width - 2, height - 2] },
    ],
    items: [],
    exits: [{ tile: [leftExit, height - 1] }, { tile: [leftExit + 1, height - 1] }],
    spawn: { tile: [leftExit, height - 2], facing: 'north' },
  };
}

await Promise.all(NEIGHBORS.map(async (neighbor, index) => {
  const world = makeInterior(neighbor, index);
  await writeFile(`${OUT}home-${neighbor[0]}.json`, `${JSON.stringify(world, null, 2)}\n`);
}));

console.log(`Wrote ${NEIGHBORS.length} neighbor interiors.`);
